### ISSUE TITLE
تغییر ریپوزیتوری

### ISSUE THREAD

**Issue by alighodrati** [EasyMicroservices/Caching#2]
موافقین این ریپوزیتوری شکسته بشه به
caching.memory
caching.redis
caching.sqlite
cachinq.sql
از این جهت که هر ریپوزیتوری پیاده سازی و wrapper های خودش رو داره
نظرتون؟
@Ali-YousefiTelori  @Mohsen-Yaghoubi  @mahdidelzendeh72

**Comment by Ali-YousefiTelori** [comment]
@alighodrati 
do you mean to make an interface for Redis and an interface for SQLite and another interface for SQL?

**Comment by mahdidelzendeh72** [comment]
به نظرم کش میتونه پیاده سازی های مختلف داشته باشه
یعنی یک سری میتونند در حافظه نگهداری بشن
یا در دیتابیس های مختلف
سختی کار دقیقا همینه که بتونیم یکپارچه کنیمشون

@alighodrati

**Comment by Mohsen-Yaghoubi** [comment]
بنظر من اینکه بخوایم به ازای هر پکیج یک ریپازیتوری بزنیم جالب نیست حجم ریپازیتوری ها میره بالا.
بهتره در یک ریپازیتوری بیایم و این کاری که شما فرمودید رو انجام بدیم مثل پروژه FileManager

**Comment by alighodrati** [comment]
موافقم با هردو
@Mohsen-Yaghoubi @mahdidelzendeh72 
شاید بهتر باشه این طوری بپرسم پیشنهادتون برای ساختار سولوشن و پروژه ها به چه صورت هست

- csharp
-- redis
 --- stackexchange
 --- easycaching
 --- ...
-- memory
 --- .net
 --- ...

اگر روال به این صورت هست که میتونم یک استراکچر پیشنهادی بزنم و پول ریکویستش رو بزارم بگین که همین طوری برم. چون حس کردم برای استراکچر گلی ها اول یک هماهنگی انجام میشه
@Ali-YousefiTelori  FYI

**Comment by Ali-YousefiTelori** [comment]
@alighodrati 
با این موافقم.
همه اش توی یک سلوشن هست، اگرم چیزی هست که به ردیس دیپند هست میره توی پوشه ی ردیس ولی همه طبق گفته ی محسن ساختار اینترفیس رو رعایت میکنن.

و این نکته رو هم در نظر بگیرید که ما میکروسرویس کشینگ قرار نیست اینجا انجام بدیم، قراره کلا ابزار های کش رو یکپارچه کنیم.
